version: '3.4'

networks: 
  deepmesh-net:

volumes:
  kong-datastore:
  keycloak-datastore:

services:
  kong-db:
    image: postgres:9.6
    volumes:
    - kong-datastore:/var/lib/postgresql/data
    networks:
    - deepmesh-net
    ports:
    - "15432:5432"
    environment:
      POSTGRES_USER:     kong
      POSTGRES_DB:       kong
      POSTGRES_PASSWORD: kong

  kong:
    # build: .
    image: kong:0.14.1-centos-oidc
    depends_on:
    - kong-db
    networks:
    - deepmesh-net
    ports:
    - "8000:8000" # Listener
    - "8001:8001" # Admin API
    - "8443:8443" # Listener  (SSL)
    - "8444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_USER:          kong
      KONG_PG_DATABASE:      kong
      KONG_PG_PASSWORD:      kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          oidc

  kong-dashboard:
    image: pgbi/kong-dashboard:v3.5.0
    depends_on:
    - kong
    command: start --kong-url http://kong:8001
    networks:
    - deepmesh-net
    ports:
    - "8280:8080"

  keycloak-db:
    image: postgres:9.6
    volumes: 
    - keycloak-datastore:/var/lib/postgresql/data
    networks:
    - deepmesh-net
    ports:
    - "25432:5432"
    environment:
      POSTGRES_USER:     keycloak
      POSTGRES_DB:       keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: jboss/keycloak-theme:4.8.3.Final
    depends_on:
    - keycloak-db
    networks:
    - deepmesh-net
    ports:
    - "8180:8080"
    environment:
      DB_VENDOR:         POSTGRES
      DB_ADDR:           keycloak-db
      DB_PORT:           5432
      DB_DATABASE:       keycloak
      DB_USER:           keycloak
      DB_PASSWORD:       keycloak
      KEYCLOAK_USER:     admin
      KEYCLOAK_PASSWORD: admin
      TZ:                Asia/Shanghai

  nginx:
    image: nginx:1.15.8-alpine
    depends_on:
    - keycloak
    - kong-dashboard
    - kong
    networks:
    - deepmesh-net
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
